customhost = "database-1.cfcp9dyqsuzb.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "wongjiahe-employee"
customregion = "us-east-1"
